### ISSUE TITLE
_include/people is corrupted

### ISSUE THREAD

**Issue by andreabedini** [swcarpentry/website-archive#37]
All files contain broken html like the following:

```
<p id="blischak.j" data-toggle="tooltip" title="<img src='{{site.filesurl}}/people/blischak.j.jpg' alt='John Blischak' />">
```

I don't know what the files are generated from so I can't fix it.

I discovered this while working to move everything into _data where is more appropriate. This would also remove the need for the python scripts.

**Comment by gvwilson** [comment]
Yeah, that threw me too, but it works in the existing web site - have a 
look in the https://github.com/swcarpentry/site repository in 
_includes/people/*.html (where these files were copied from), and then 
at http://software-carpentry.org/pages/team.html (where the popups 
display properly).

Regarding the source of the files, they're created by hand - every time 
someone becomes an instructor, we create a file like this for them by 
copying an existing one and modifying the values.  That worked fine when 
there were just a dozen of us, and there was a never a moment when I had 
the time to re-think it.

**Comment by andreabedini** [comment]
ahhh, no, it's fine. the tooltip is the image, so the img tag is actually inside the title attribute. all good :)

**Comment by gvwilson** [comment]
I should still generate these from a file in _data somehow, but we'll 
figure that out after we get the existing scheme working. Still don't 
understand why it works on the old website but not the new one - I 
_think_ all the JS is copied over...

**Comment by andreabedini** [comment]
yeah, I did some tests on how to put those files into data and it seems to work ok. the files will have the following format

in `_data/people/wilson.g.yaml`

``` yaml
id: wilson.g
name: Greg Wilson
biography: '[Greg Wilson](http://www.third-bit.com) started the Software Carpentry
  project in 1998. He has been a professional software developer, an author, and a
  university professor. Greg received his PhD in Computer Science from the University
  of Edinburgh in 1993.'
```

The data can be accessed as `site.data.people.wilsong`. The dot gets eaten (because `site.data.people.wilson.g` would mean the wrong thing), that's why I have to replicate the id in the id field. Biography can easily be markdown.

Generating the current

``` html
<p id="wilson.g" data-toggle="tooltip" title="<img src='{{page.root}}/img/people/wilson.g.jpg' alt='Greg Wilson' />">
    <a href="http://www.third-bit.com" class="person">Greg Wilson</a>
    started the Software Carpentry project in 1998. He has been a
    professional software developer, an author, and a university
    professor. Greg received his PhD in Computer Science from the
    University of Edinburgh in 1993.
    <br/>
    <strong>Executive Director</strong>
</p>
```

should be easy.

PS: I noticed only now the `Executive Director` at the bottom. I can be either put in the markdown or as a special field (role?). A role field can also be used to automatise pages/scf.html
